spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_rc
    username: tntrol
    password: dfkjd
jwt:
  secret: it_is_dont_security
server:
  port: 16001
mail:
  address: localhost:16000/email
keycloak:
  address: localhost:8080/auth/realms/Mail/protocol/openid-connect/token
  password: password
  username: user1
  client_id: mail
  grant_type: password