spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop_rc
    username: tntrol
    password: dfkjd
  application:
    name: store
message:
  topic:
    name: queue1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
store:
  address: "bolshoe sadovoe 302bis 50"
jwt:
  secret: it_is_dont_security
server:
  port: 16001
keycloak:
  address: localhost:8080/auth/realms/Mail/protocol/openid-connect/token
  password: password
  username: user1
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


